---
name: Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-shared:
    uses: ruromero/exhort-integration-tests/.github/workflows/integration.yml@sdk-common
    with:
      language: javascript
      repo-url: ${{ github.repository }}
      commit-sha: ${{ github.sha }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}